# Generated by Django 5.2.10 on 2026-02-07 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='モデル名')),
                ('api_url', models.URLField(verbose_name='推論APIのURL')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='RetrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='training_images/', verbose_name='手書き画像')),
                ('predicted_digit', models.CharField(max_length=1, verbose_name='AI予測値')),
                ('correct_digit', models.CharField(max_length=1, verbose_name='修正正解値')),
                ('is_incorrect', models.BooleanField(default=False, verbose_name='間違いフラグ')),
                ('model_version', models.CharField(max_length=100, verbose_name='モデル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='batch_id',
            field=models.CharField(db_index=True, max_length=36, verbose_name='バッチID（共通ID）'),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='digit_index',
            field=models.PositiveSmallIntegerField(verbose_name='桁の順序'),
        ),
    ]
